using Microsoft.EntityFrameworkCore;
using ConferenceManagement.Api.Models;

namespace ConferenceManagement.Api.Data;

public class EventStoreDbContext(DbContextOptions<EventStoreDbContext> options) : DbContext(options)
{
    public DbSet<ConferenceEvent> Events => Set<ConferenceEvent>();
    public DbSet<Conference> Conferences => Set<Conference>();
    public DbSet<SeatAvailability> SeatAvailabilities => Set<SeatAvailability>();
    public DbSet<Booking> Bookings => Set<Booking>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Event store — append-only, sequence generated by DB
        modelBuilder.Entity<ConferenceEvent>(e =>
        {
            e.ToTable("events");
            e.HasKey(x => x.Id);
            e.Property(x => x.Id).HasColumnName("id");
            e.Property(x => x.ConferenceId).HasColumnName("conference_id");
            e.Property(x => x.EventType).HasColumnName("event_type").HasMaxLength(100);
            e.Property(x => x.Payload).HasColumnName("payload").HasColumnType("jsonb");
            e.Property(x => x.OccurredAt).HasColumnName("occurred_at");
            e.Property(x => x.SequenceNumber)
                .HasColumnName("sequence_number")
                .ValueGeneratedOnAdd();
            e.HasIndex(x => x.ConferenceId).HasDatabaseName("ix_events_conference_id");
            e.HasIndex(x => x.SequenceNumber).HasDatabaseName("ix_events_sequence");
        });

        // Conferences
        modelBuilder.Entity<Conference>(e =>
        {
            e.ToTable("conferences");
            e.HasKey(x => x.Id);
            e.Property(x => x.Id).HasColumnName("id");
            e.Property(x => x.Name).HasColumnName("name").HasMaxLength(255);
            e.Property(x => x.TotalSeats).HasColumnName("total_seats");
            e.Property(x => x.CreatedAt).HasColumnName("created_at");
        });

        // Materialized view — seat availability
        modelBuilder.Entity<SeatAvailability>(e =>
        {
            e.ToTable("seat_availability");
            e.HasKey(x => x.ConferenceId);
            e.Property(x => x.ConferenceId).HasColumnName("conference_id");
            e.Property(x => x.ConferenceName).HasColumnName("conference_name").HasMaxLength(255);
            e.Property(x => x.TotalSeats).HasColumnName("total_seats");
            e.Property(x => x.BookedSeats).HasColumnName("booked_seats");
            e.Property(x => x.LastEventSequence).HasColumnName("last_event_sequence");
            e.Property(x => x.UpdatedAt).HasColumnName("updated_at");
            e.Ignore(x => x.AvailableSeats);
        });

        // Bookings
        modelBuilder.Entity<Booking>(e =>
        {
            e.ToTable("bookings");
            e.HasKey(x => x.Id);
            e.Property(x => x.Id).HasColumnName("id");
            e.Property(x => x.ConferenceId).HasColumnName("conference_id");
            e.Property(x => x.AttendeeName).HasColumnName("attendee_name").HasMaxLength(255);
            e.Property(x => x.AttendeeEmail).HasColumnName("attendee_email").HasMaxLength(255);
            e.Property(x => x.BookedAt).HasColumnName("booked_at");
            e.Property(x => x.IsCancelled).HasColumnName("is_cancelled");
            e.Property(x => x.CancelledAt).HasColumnName("cancelled_at");
            e.HasIndex(x => x.ConferenceId).HasDatabaseName("ix_bookings_conference_id");
        });
    }
}
